# Generated by Django 3.0 on 2022-04-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsWorkingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_script', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4')], max_length=20)),
                ('branch', models.CharField(choices=[('PUC1', 'PUC1'), ('PUC2', 'PUC2'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('CE', 'CIVIL'), ('ME', 'MECHANICAL'), ('CHEM', 'CHEMICAL'), ('MME', 'MME')], max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarkAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4')], max_length=20)),
                ('branch', models.CharField(choices=[('PUC1', 'PUC1'), ('PUC2', 'PUC2'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('CE', 'CIVIL'), ('ME', 'MECHANICAL'), ('CHEM', 'CHEMICAL'), ('MME', 'MME')], max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('attendance_marked_date', models.DateField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
    ]
