# Generated by Django 3.0 on 2022-04-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isworkingday',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
